services:
  # Django Producer Service (Solo REST API + HOT RELOAD)
  producer-and-server:
    build: . # Finds the DockerFile
    ports:
      - "8000:8000"
    volumes:
      # 🔥 HOT RELOAD: Mount source code for live development
      - .:/app
      - /app/django_project_env  # Exclude virtual env
    environment:
      - MONGO_DB=my_first_ci_db
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - WEBSOCKET_ENABLED=false  # Disable WebSocket for solo development
    depends_on:
      - mongo
    networks:
      - dev-network
    command: python manage.py runserver 0.0.0.0:8000  # Force runserver for hot reload



  # MongoDB Database
  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: my_first_ci_db
    volumes:
      - mongo_data_dev:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  mongo_data_dev: 