name: Build and Push Docker Images

on:
  push:
    branches: [ master, main ]
    paths:
      - 'Chapter-Threads/Projects/**'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'Chapter-Threads/Projects/**'
  workflow_dispatch:  # Permite ejecutar manualmente

env:
  NAMESPACE: pipe17049  # Cambia por tu namespace en Docker Hub

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: master
    strategy:
      matrix:
        include:
          - image: api
            dockerfile: Chapter-Threads/Projects/docker/Dockerfile.api.final
            context: Chapter-Threads/Projects
          - image: worker
            dockerfile: Chapter-Threads/Projects/docker/Dockerfile.worker.final
            context: Chapter-Threads/Projects

    steps:
    - name: 🔄 Checkout repository
      uses: actions/checkout@v4

    - name: 🐳 Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 🔑 Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 📝 Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: docker.io/${{ env.NAMESPACE }}/threads-${{ matrix.image }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: 🔨 Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.dockerfile }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

    - name: 📋 Image Summary
      if: github.event_name != 'pull_request'
      run: |
        echo "### 🎯 Built Images" >> $GITHUB_STEP_SUMMARY
        echo "| Image | Tags |" >> $GITHUB_STEP_SUMMARY
        echo "|-------|------|" >> $GITHUB_STEP_SUMMARY
        echo "| threads-${{ matrix.image }} | \`${{ steps.meta.outputs.tags }}\` |" >> $GITHUB_STEP_SUMMARY